"""
Agent Tools

MCP tools for creating Eliza agents (RAG, Function-calling).
Returns .env file content for Cascade to write (triggers validation hooks).

VALIDATION: All inputs are validated before API calls.
"""

import os
from mcp.types import Tool
from typing import Dict, Any
from api.client import ElizaClient, COGENGINE_URLS
from validation import validate_create_agent_inputs, format_validation_errors


def generate_env_content_for_agent(agent_id: str, env: str = "QA") -> str:
    """
    Generate .env file content for agent credentials.

    NOTE: This function NO LONGER writes files directly.
    Instead, it returns the content that Cascade should write.

    Args:
        agent_id: The agent ID to save
        env: The Eliza environment

    Returns:
        .env file content as string
    """
    lines = [
        "# Eliza Configuration (generated by Eliza MCP Server)",
        "",
        f"ELIZA_AGENT_ID={agent_id}",
        f"ELIZA_ENV={env}",
        ""
    ]
    return "\n".join(lines)


# Tool definitions
AGENT_TOOLS = [
    Tool(
        name="create_rag_agent",
        description="""Create an Eliza agent for DOCUMENT Q&A (RAG - Retrieval Augmented Generation).

USE THIS WHEN: User wants an agent that answers questions from uploaded documents/PDFs/text.

⚠ BEFORE CALLING - You MUST ask the user for:
1. jwt_token - Ask: "Please provide your Eliza JWT token for authentication"
2. initiative_id - Ask: "What is your initiative ID? (format: ELZI-{userid}, e.g., ELZI-XFMLC5G)"
3. env - Ask: "Which environment? (DEV, TEST, QA, or PROD)" - default QA if not specified
4. agent_name - Ask: "What should the agent be named?"

DO NOT call this tool with placeholder values. Get real values from the user first.

CAPABILITY: Creates agent with retriever_strategy="STANDARD" for document-based Q&A.""",
        inputSchema={
            "type": "object",
            "properties": {
                "jwt_token": {
                    "type": "string",
                    "description": "⚠ REQUIRED - User's Eliza JWT token. ASK USER if not provided."
                },
                "initiative_id": {
                    "type": "string",
                    "description": "⚠ REQUIRED - User's initiative ID (format: ELZI-{userid}). ASK USER if not provided."
                },
                "env": {
                    "type": "string",
                    "enum": ["DEV", "TEST", "QA", "PROD"],
                    "description": "Eliza environment. Default: QA"
                },
                "agent_name": {
                    "type": "string",
                    "description": "Name for the agent. ASK USER if not provided."
                },
                "agent_description": {
                    "type": "string",
                    "description": "What the agent does"
                },
                "system_prompt": {
                    "type": "string",
                    "description": "Instructions for how the agent should behave"
                }
            },
            "required": ["jwt_token", "initiative_id", "agent_name"]
        }
    ),
    Tool(
        name="create_function_agent",
        description="""Create an Eliza agent that can call FUNCTIONS/TOOLS.

USE THIS WHEN: User wants an agent with tools, functions, or capabilities beyond document Q&A.

⚠ BEFORE CALLING - You MUST ask the user for:
1. jwt_token - Ask: "Please provide your Eliza JWT token for authentication"
2. initiative_id - Ask: "What is your initiative ID? (format: ELZI-{userid}, e.g., ELZI-XFMLC5G)"
3. env - Ask: "Which environment? (DEV, TEST, QA, or PROD)" - default QA if not specified
4. agent_name - Ask: "What should the agent be named?"

DO NOT call this tool with placeholder values. Get real values from the user first.

CAPABILITY: Creates agent with retriever_strategy="REASON" which enables function calling.""",
        inputSchema={
            "type": "object",
            "properties": {
                "jwt_token": {
                    "type": "string",
                    "description": "⚠ REQUIRED - User's Eliza JWT token. ASK USER if not provided."
                },
                "initiative_id": {
                    "type": "string",
                    "description": "⚠ REQUIRED - User's initiative ID (format: ELZI-{userid}). ASK USER if not provided."
                },
                "env": {
                    "type": "string",
                    "enum": ["DEV", "TEST", "QA", "PROD"],
                    "description": "Eliza environment. Default: QA"
                },
                "agent_name": {
                    "type": "string",
                    "description": "Name for the agent. ASK USER if not provided."
                },
                "agent_description": {
                    "type": "string",
                    "description": "What the agent does"
                },
                "system_prompt": {
                    "type": "string",
                    "description": "Instructions for how the agent should behave and use tools"
                }
            },
            "required": ["jwt_token", "initiative_id", "agent_name"]
        }
    )
]

# NOTE: get_agent_template REMOVED - it caused AI to write files instead of using APIs


# Tool implementations
def create_rag_agent(args: Dict[str, Any]) -> str:
    """Create a RAG agent for document Q&A - LIVE EXECUTION."""
    jwt_token = args.get("jwt_token", "")
    initiative_id = args.get("initiative_id", "")
    env = args.get("env", "QA")
    agent_name = args.get("agent_name", "Document Q&A Agent")
    agent_desc = args.get("agent_description", "Answers questions from uploaded documents")
    system_prompt = args.get("system_prompt", "You are a helpful assistant that answers questions based on the provided documents.")

    # VALIDATION FIRST - Block on any validation error
    validation = validate_create_agent_inputs(jwt_token, initiative_id, env)
    if not validation.valid:
        error_msg = format_validation_errors(validation)
        return f"""❌ VALIDATION FAILED - AGENT NOT CREATED

{error_msg}

Please provide valid values and try again.
"""

    if jwt_token and initiative_id:
        try:
            import bnym_eliza as eliza
            from bnym_eliza.genai.agent import Agent

            eliza.session = eliza.Session.connect(
                env=env,
                jwt_token=jwt_token,
                initiative_id=initiative_id
            )

            agent = Agent(
                env=env,
                agent_name=agent_name,
                agent_description=agent_desc,
                llm_model='bnym-llama-3.3-70b-instruct',
                retriever_strategy='STANDARD',
                prompt=system_prompt,
                welcome_message='Hello! I can answer questions about the documents I have access to.',
                control_flags=['ADD_KNOWLEDGE', 'USE_HISTORY']
            )

            agent.create()

            # Generate .env content for Cascade to write
            env_content = generate_env_content_for_agent(agent.agent_id, env)

            return f'''✅ RAG AGENT CREATED SUCCESSFULLY!

Agent ID: {agent.agent_id}
Name: {agent_name}
Environment: {env}
Strategy: STANDARD (document Q&A / RAG)
Model: bnym-llama-3.3-70b-instruct

📄 NEXT STEPS - Upload documents:
Use create_document_upload with agent_id="{agent.agent_id}"

The agent is live and ready to use in Workbench!

---

## 📁 REQUIRED: Write .env File

**You MUST write this file using your edit tools** to enable validation hooks.

**Path**: `{{workspace}}/.env` (replace {{workspace}} with actual workspace path)

```
{env_content}
```

**⚠ IMPORTANT**: Use `write_to_file` tool to create this file.
'''
        except Exception as e:
            return f'''❌ RAG AGENT CREATION FAILED

Error: {str(e)}

Troubleshooting:
• Check JWT token is valid and not expired
• Verify initiative_id format: ELZI-{{userid}}
• Ensure you have access to environment: {env}
'''

    # No JWT - return template code
    return f'''# RAG AGENT - Document Q&A
# ⚠ JWT not provided - returning code template to run manually

import bnym_eliza as eliza
from bnym_eliza.genai.agent import Agent
from bnym_eliza.utils import get_jwt

jwt_token = get_jwt()
eliza.session = eliza.Session.connect(
    env='QA',
    jwt_token=jwt_token,
    initiative_id='ELZI-{{YOUR_USERID}}'
)

agent = Agent(
    env='QA',
    agent_name='{agent_name}',
    agent_description='{agent_desc}',
    llm_model='bnym-llama-3.3-70b-instruct',
    retriever_strategy='STANDARD',
    prompt='{system_prompt}',
    control_flags=['ADD_KNOWLEDGE', 'USE_HISTORY']
)
agent.create()
print(f"Agent ID: {{agent.agent_id}}")
'''


def create_function_agent(args: Dict[str, Any]) -> str:
    """Create an agent with function calling capability - LIVE EXECUTION."""
    jwt_token = args.get("jwt_token", "")
    initiative_id = args.get("initiative_id", "")
    env = args.get("env", "QA")
    agent_name = args.get("agent_name", "Function Agent")
    agent_desc = args.get("agent_description", "An agent that can use tools and functions")
    system_prompt = args.get("system_prompt", "You are a helpful assistant with access to various tools.")

    # VALIDATION FIRST - Block on any validation error
    validation = validate_create_agent_inputs(jwt_token, initiative_id, env)
    if not validation.valid:
        error_msg = format_validation_errors(validation)
        return f"""❌ VALIDATION FAILED - AGENT NOT CREATED

{error_msg}

Please provide valid values and try again.
"""

    if jwt_token and initiative_id:
        try:
            import bnym_eliza as eliza
            from bnym_eliza.genai.agent import Agent

            eliza.session = eliza.Session.connect(
                env=env,
                jwt_token=jwt_token,
                initiative_id=initiative_id
            )

            agent = Agent(
                env=env,
                agent_name=agent_name,
                agent_description=agent_desc,
                llm_model='openai-gpt-4.1-mini-ptu',
                retriever_strategy='REASON',
                prompt=system_prompt,
                welcome_message='Hello! I can help you with various tasks using my available tools.',
                control_flags=['USE_HISTORY', 'USE_MEMORY']
            )

            agent.create()

            # Generate .env content for Cascade to write
            env_content = generate_env_content_for_agent(agent.agent_id, env)

            return f'''✅ AGENT CREATED SUCCESSFULLY!

Agent ID: {agent.agent_id}
Name: {agent_name}
Environment: {env}
Strategy: REASON (function calling enabled)
Model: openai-gpt-4.1-mini-ptu

🔧 NEXT STEPS - Add functions to your agent:
Use create_nugget or create_*_function tools with agent_id="{agent.agent_id}"

The agent is live and ready to use in Workbench!

---

## 📁 REQUIRED: Write .env File

**You MUST write this file using your edit tools** to enable validation hooks.

**Path**: `{{workspace}}/.env` (replace {{workspace}} with actual workspace path)

```
{env_content}
```

**⚠ IMPORTANT**: Use `write_to_file` tool to create this file.
'''
        except Exception as e:
            return f'''❌ AGENT CREATION FAILED

Error: {str(e)}

Troubleshooting:
• Check JWT token is valid and not expired
• Verify initiative_id format: ELZI-{{userid}}
• Ensure you have access to the environment: {env}
'''

    # No JWT - return template code
    return f'''# FUNCTION AGENT - With retriever_strategy="REASON" for tool calling
# ⚠ JWT not provided - returning code template to run manually

import bnym_eliza as eliza
from bnym_eliza.genai.agent import Agent
from bnym_eliza.utils import get_jwt

jwt_token = get_jwt()
eliza.session = eliza.Session.connect(
    env='QA',
    jwt_token=jwt_token,
    initiative_id='ELZI-{{YOUR_USERID}}'
)

agent = Agent(
    env='QA',
    agent_name='{agent_name}',
    agent_description='{agent_desc}',
    llm_model='openai-gpt-4.1-mini-ptu',
    retriever_strategy='REASON',
    prompt='{system_prompt}',
    control_flags=['USE_HISTORY', 'USE_MEMORY']
)
agent.create()
print(f"Agent ID: {{agent.agent_id}}")
'''


def get_agent_template(args: Dict[str, Any]) -> str:
    """
    DEPRECATED: Do not return raw agent code templates.

    Agents should be created via MCP tools (create_function_agent, create_rag_agent)
    which handle authentication, validation, and API calls properly.
    """
    strategy = args.get("retriever_strategy", "STANDARD")
    with_funcs = args.get("with_functions", False)

    # DO NOT RETURN RAW CODE - it causes AI to write files instead of using APIs
    agent_type = "function-calling agent" if strategy == "REASON" or with_funcs else "RAG/document Q&A agent"
    mcp_tool = "create_function_agent" if strategy == "REASON" or with_funcs else "create_rag_agent"

    return f"""🚫 **STOP - DO NOT WRITE AGENT CODE TO FILES**

You requested a `{strategy}` agent template, but **agents should be created via MCP tools, not by writing Python files**

## ⚠ WHY NOT WRITE CODE FILES?

When you write Python code to files:
1. The code has placeholder values that won't work
2. Users have to manually edit and run it
3. Validation doesn't happen until runtime (too late!)
4. You often hallucinate incorrect SDK methods

## ✅ REQUIRED WORKFLOW

**Step 1: Ask user for credentials**
```
"Please provide:
1. Your Eliza JWT token
2. Your initiative ID (format: ELZI-{{your_userid}})
3. What should the agent be named?
4. What should the agent do?"
```

**Step 2: Use the correct MCP tool**
```
Call: {mcp_tool}
With: jwt_token, initiative_id, agent_name, agent_description, system_prompt
```

This will:
- Create the agent via Eliza API immediately
- Return the real agent_id
- Handle all authentication
- Validate everything works

## For {agent_type}:

{"**If you need nuggets/tools on this agent:**" if strategy == "REASON" or with_funcs else "**If you need to upload documents:**"}
{("Step 3: Call search_ez_functions (discover what ez* functions you need)" + chr(10) + "Step 4: Call create_nugget (creates nugget on the agent via API)" + chr(10) + chr(10) + "The create_nugget tool will:" + chr(10) + "- Generate validated JavaScript code" + chr(10) + "- Create the nugget via API" + chr(10) + "- Create a callable function on the agent" + chr(10) + "- Return the nugget_id") if strategy == "REASON" or with_funcs else ("Step 3: Call create_document_upload (generates upload code)")}

## 🚫 DO NOT:
- Write Python files with agent creation code
- Use placeholder values like 'ELZI-{{YOUR_USERID}}'
- Create agents without getting JWT token from user first

**START NOW**: Ask the user for their JWT token, initiative ID, and agent requirements.
"""