"""
Nugget Tools

MCP tools for creating and managing Eliza nuggets.
Includes the search_ez_functions tool for discovering function signatures.

Pipeline:
1. search_ez_functions - discover what ez* functions to use
2. create_nugget - generates code, validates, creates via API

TIER 1 CREATE TOOLS: create_nugget is a CREATE operation that benefits from
workflow state but can also work with direct jwt_token/agent_id input.

VALIDATION: All inputs are validated before API calls.
"""

from mcp.types import Tool
from typing import Dict, Any
from search.search import search_ez_functions, format_search_results
from codegen.nugget_generator import generate_nugget_code
from api.client import COGENGINE_URLS
from validation.static import validate_code, Severity
from validation import validate_create_nugget_inputs, format_validation_errors
from tools.workflow_state import resolve_workspace_path, load_state, is_credentials_only_state, ensure_credentials
import json
import os
import re
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def generate_env_file_content(jwt_token: str, agent_id: str, env: str = "QA") -> str:
    """
    Generate .env file content for Eliza credentials.

    NOTE: This function NO LONGER writes files directly.
    Instead, it returns the content that Cascade should write.

    Args:
        jwt_token: Eliza JWT token
        agent_id: Agent UUID
        env: Eliza environment (DEV/TEST/QA/PROD)

    Returns:
        .env file content as string
    """
    lines = [
        "# Eliza credentials for nugget validation",
        "# Generated by Eliza MCP Server",
        "",
        f"ELIZA_JWT_TOKEN={jwt_token}",
        f"ELIZA_AGENT_ID={agent_id}",
        f"ELIZA_ENV={env}",
        ""
    ]
    return "\n".join(lines)


def generate_nugget_file_content(code: str, label: str, agent_id: str) -> str:
    """
    Generate nugget file content with header metadata.

    NOTE: This function NO LONGER writes files directly.
    Instead, it returns the content that Cascade should write.

    Args:
        code: The JavaScript nugget code
        label: The nugget label
        agent_id: The agent ID

    Returns:
        Complete file content as string
    """
    return f"""/**
* Eliza Nugget: {label}
* Agent ID: {agent_id}
* Generated by: Eliza MCP Server
*
* This file is auto-generated. The nugget code below is deployed to Eliza.
* Editing this file will NOT update the deployed nugget.
*/

{code}
"""


def generate_nugget_file_path(label: str, agent_id: str, workspace_path: str) -> str:
    """
    Generate the file path where nugget should be written.

    Args:
        label: The nugget label (used for filename)
        agent_id: The agent ID (used for subdirectory)
        workspace_path: Absolute path to user's workspace root

    Returns:
        Absolute file path
    """
    agent_short = agent_id[:8] if len(agent_id) > 8 else agent_id
    safe_label = re.sub(r'[^a-zA-Z0-9_-]', '_', label.lower())
    safe_label = re.sub(r'_+', '_', safe_label).strip('_')
    filename = f"{safe_label}.nugget.js"
    return os.path.join(workspace_path, "nuggets", agent_short, filename)


# Tool definitions
NUGGET_TOOLS = [
    Tool(
        name="search_ez_functions",
        description="""🔍 DISCOVERY TOOL - Search for ez* functions needed for a task.

USE THIS FIRST when creating nuggets. Returns correct signatures and examples.

⚠ IMPORTANT: Call this BEFORE create_nugget to discover which functions you need.

AVAILABLE CATEGORIES (52 functions):
• COMMUNICATION: ezMail, ezChat, ezNotify, ezComms, ezConfirm
• SEARCH: ezInternetSearch, ezGenAISearch, ezDataSearch
• AI/LLM: ezChatCompletions, ezEmbeddings, ezImageToText, ezTextToImage, ezTextToVideo, ezTextToSpeech
• DATA: ezSqlSelect, ezSaveSessionData, ezGetSessionData, ezDataQuery, ezDataCreate
• INTEGRATION: ezNexenApi, ezJiraSupport, ezSharePoint, ezA2A, ezMCP, ezApi, ezCopilotChat
• UTILITY: ezLog, ezUserLog, ezNugget, ezFunction, ezJson, sleep
• USER/AUTH: ezUser, ezSecret, ezToken
• AUTOMATION: ezBrowser, ezComputer, ezCanvas, ezPython, ezJavaScript

Search examples:
- "send email" → ezMail
- "search internet news" → ezInternetSearch
- "call LLM summarize" → ezChatCompletions
- "jira ticket" → ezJiraSupport
- "sharepoint document" → ezSharePoint
- "agent to agent" → ezA2A

Returns function signatures, examples, and status (WORKS/NEEDS_CONFIG/QA_LIMITED).""",
        inputSchema={
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "What capabilities you need (e.g., 'send email', 'search internet', 'call LLM')"
                },
                "max_results": {
                    "type": "integer",
                    "description": "Maximum number of functions to return (default: 5)"
                }
            },
            "required": ["query"]
        }
    ),
    Tool(
        name="create_nugget",
        description="""Create and VALIDATE a JavaScript nugget on an Eliza agent.

🚫 **WORKFLOW ENFORCEMENT** (Jan 2026):
- You MUST call search_ez_functions FIRST to discover functions
- Or set skip_search=true if you already know the exact ez* functions
- Static validation runs BEFORE any API calls
- If validation fails, the nugget is NOT created

⚠ REQUIRED WORKFLOW:
1. FIRST call search_ez_functions to discover what functions you need
2. THEN call this tool with the discovered functions

⚠ BEFORE CALLING - You MUST have:
1. jwt_token - Ask user: "Please provide your Eliza JWT token"
2. agent_id - Ask user: "What is the agent ID to add this nugget to?"
3. discovered_functions - From search_ez_functions OR known functions with skip_search=true

This tool will:
1. **VALIDATE FUNCTIONS** - Ensure discovered_functions exist in the index
2. **STATIC VALIDATION** - Check code syntax and patterns (BLOCKS on failure)
3. Generate JavaScript code using discovered function signatures
4. Create the nugget on the agent via API
5. Create a callable function
6. Validate by executing
7. **Return file write instructions** - YOU MUST write the files using edit tools

📁 **FILE WRITING**:
- MCP does NOT write files directly
- On success, you receive explicit instructions with file paths and content
- YOU MUST use `write_to_file` tool to create the files
- This triggers Windsurf hooks for additional validation""",
        inputSchema={
            "type": "object",
            "properties": {
                "jwt_token": {
                    "type": "string",
                    "description": "REQUIRED - User's Eliza JWT token"
                },
                "agent_id": {
                    "type": "string",
                    "description": "REQUIRED - UUID of the agent to add nugget to"
                },
                "requirement": {
                    "type": "string",
                    "description": "What the nugget should do"
                },
                "discovered_functions": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "REQUIRED - List of ez* function names from search_ez_functions"
                },
                "skip_search": {
                    "type": "boolean",
                    "description": "Set true ONLY if you already know the exact ez* functions. Bypasses workflow check."
                },
                "label": {
                    "type": "string",
                    "description": "Display name for the nugget"
                },
                "email": {
                    "type": "string",
                    "description": "Email address if nugget sends email"
                },
                "query": {
                    "type": "string",
                    "description": "Default search query if nugget searches"
                },
                "prompt": {
                    "type": "string",
                    "description": "When LLM should use this nugget"
                },
                "params": {
                    "type": "array",
                    "description": "Input parameters: [{paramNameKey, paramType, paramDescription, optional}]",
                    "items": {"type": "object"}
                },
                "make_callable": {
                    "type": "boolean",
                    "description": "Create function so agent can call nugget (default: true)"
                },
                "skip_validation": {
                    "type": "boolean",
                    "description": "NOT RECOMMENDED - Skip static validation. Only use for debugging."
                },
                "env": {
                    "type": "string",
                    "enum": ["DEV", "TEST", "QA", "PROD"],
                    "description": "Eliza environment. Default: QA"
                },
                "workspace_path": {
                    "type": "string",
                    "description": "Workspace absolute path for file write instructions."
                }
            },
            "required": ["jwt_token", "agent_id", "requirement"]
        }
    )
]


# Tool implementations
def handle_search_ez_functions(args: Dict[str, Any]) -> str:
    """Search for ez* functions matching a query."""
    query = args.get("query", "")
    max_results = args.get("max_results", 5)

    results = search_ez_functions(query, max_results)

    if not results:
        return f"""No ez* functions found matching "{query}".

Try different keywords:
- For email: "email", "mail", "send", "notify"
- For search: "search", "internet", "google", "news"
- For AI: "llm", "chat", "gpt", "summarize", "analyze"
- For data: "session", "save", "store", "database"
"""

    output = format_search_results(results)

    # Add next step instructions
    function_names = [r["name"] for r in results]
    output += f"""

## Next Step

Use these discovered functions with `create_nugget`:
```
discovered_functions: {json.dumps(function_names)}
```
"""

    return output


async def handle_create_nugget(args: Dict[str, Any]) -> str:
    """
    Create and validate a nugget using discovered functions.

    **WORKFLOW ENFORCEMENT** (Jan 2026):
    - discovered_functions is required unless skip_search=true
    - Static validation runs BEFORE any API calls
    - If validation fails, nugget is NOT created
    - This prevents invalid nuggets from being deployed
    - Supports credential lookup from workflow state
    """
    jwt_token = args.get("jwt_token")
    agent_id = args.get("agent_id")
    requirement = args.get("requirement", "")
    discovered_functions = args.get("discovered_functions", [])
    skip_search = args.get("skip_search", False)  # Override for workflow enforcement
    custom_label = args.get("label")
    email = args.get("email")
    query = args.get("query")
    custom_prompt = args.get("prompt")
    custom_params = args.get("params", [])
    make_callable = args.get("make_callable", True)
    skip_validation = args.get("skip_validation", False)  # Emergency escape hatch
    env = args.get("env", "QA")
    workspace_path = args.get("workspace_path")  # For writing files to trigger hooks

    # =================================================================
    # WORKSPACE RESOLUTION AND CREDENTIAL LOOKUP
    # =================================================================
    resolved_workspace, ws_error = resolve_workspace_path(args)

    # ENFORCE workspace path - must have .eliza/ tracking
    if ws_error:
        return json.dumps({
            "status": "WORKSPACE_REQUIRED",
            "error": ws_error,
            "fix": "Provide workspace_path parameter pointing to your project directory. "
                   "Example: workspace_path='/path/to/your/project'. "
                   "Or run eliza_workflow(action='start') first to initialize credentials."
        })

    if resolved_workspace:
        workspace_path = workspace_path or resolved_workspace

        # Use ensure_credentials to get credentials (centralized reading)
        success, creds, cred_error = ensure_credentials(
            resolved_workspace,
            jwt_token=jwt_token or None,
            agent_id=agent_id or None,
            env=env
        )
        if success:
            # Use credentials returned by ensure_credentials (centralized reading)
            jwt_token = creds.get("jwt_token") or jwt_token
            agent_id = creds.get("agent_id") or agent_id
            env = creds.get("env") or env
        else:
            # ensure_credentials failed - return specific error
            return json.dumps({
                "status": "CREDENTIALS_REQUIRED",
                "error": cred_error,
                "fix": "Provide jwt_token and agent_id parameters, or run eliza_workflow(action='start') first."
            })

        # Check if state is CREDENTIALS_ONLY (warn but allow)
        state = load_state(resolved_workspace)
        if state and is_credentials_only_state(state):
            # Warn that they're bypassing full workflow
            print("⚠ Note: Using credentials-only state. Full workflow (eliza_workflow) provides better validation.")

    # =================================================================
    # WORKFLOW ENFORCEMENT: Require discovered_functions or skip_search
    # =================================================================
    if not discovered_functions and not skip_search:
        return """❌ **WORKFLOW ERROR: No functions discovered**

**REQUIRED WORKFLOW:**
1. Call `search_ez_functions` first to discover what ez* functions you need
2. Then call `create_nugget` with the `discovered_functions` list

**Example:**
```
# Step 1: Discover functions
search_ez_functions(query="send email notification")

# Step 2: Create nugget with discovered functions
create_nugget(
    jwt_token="...",
    agent_id="...",
    requirement="Send email notifications",
    discovered_functions=["ezMail"]
)
```

**Or if you already know the exact functions:**
```
create_nugget(
    jwt_token="...",
    agent_id="...",
    requirement="Send email notifications",
    discovered_functions=["ezMail"],
    skip_search=true  # Bypasses workflow check
)
```
"""

    # =================================================================
    # CENTRALIZED VALIDATION - JWT, agent_id, env, discovered_functions
    # =================================================================
    validation = validate_create_nugget_inputs(
        jwt_token=jwt_token or "",
        agent_id=agent_id or "",
        discovered_functions=discovered_functions,
        params=custom_params,
        env=env,
        email=email
    )

    if not validation.valid:
        error_msg = format_validation_errors(validation)
        return f"""❌ VALIDATION FAILED - NUGGET NOT CREATED

{error_msg}

Please provide valid values and try again.
"""

    # Show warnings if any (but don't block)
    if validation.warnings:
        warning_lines = []
        for w in validation.warnings:
            warning_lines.append(f"⚠ {w.field}: {w.message}")
        print("VALIDATION WARNINGS:\n" + "\n".join(warning_lines))

    # =================================================================
    # VALIDATE discovered_functions exist in EZ_FUNCTION_INDEX
    # =================================================================
    if discovered_functions:
        from search.index import EZ_FUNCTION_INDEX
        invalid_functions = []
        deprecated_functions = []

        for func in discovered_functions:
            if func not in EZ_FUNCTION_INDEX:
                invalid_functions.append(func)
            elif EZ_FUNCTION_INDEX[func].get("status") == "DEPRECATED":
                deprecated_functions.append(func)

        if invalid_functions:
            return f"""❌ **INVALID FUNCTIONS: {', '.join(invalid_functions)}**

These functions do not exist in the Eliza function index.

**Available functions:**
Use `search_ez_functions` to find valid functions.

**Common functions:**
- ezMail - Send emails
- ezInternetSearch - Search internet
- ezChatCompletions - Call LLM
- ezSaveSessionData / ezGetSessionData - Session persistence
"""

        if deprecated_functions:
            # Warn but don't block
            print(f"⚠ Warning: These functions are DEPRECATED: {', '.join(deprecated_functions)}")

    # Generate code using discovered functions
    params = {"email": email, "query": query}
    code, auto_label, auto_description, test_data = generate_nugget_code(
        discovered_functions, requirement, params
    )

    # ================================================================
    # STEP 0: MANDATORY STATIC VALIDATION (Added Dec 29, 2025)
    # This runs BEFORE any API calls to prevent invalid nuggets from being created
    # ================================================================
    if not skip_validation:
        validation_result = validate_code(code, "nugget")

        if not validation_result.valid:
            # Build detailed error report
            errors = [i for i in validation_result.issues if i.severity == Severity.ERROR]
            warnings = [i for i in validation_result.issues if i.severity == Severity.WARNING]

            error_details = []
            for e in errors:
                error_details.append(f"- ❌ {e.message}")
                if e.fix:
                    error_details.append(f"  → **Fix**: {e.fix}")

            warning_details = []
            for w in warnings:
                warning_details.append(f"- ⚠ {w.message}")
                if w.fix:
                    warning_details.append(f"  → **Fix**: {w.fix}")

            # Provide auto-fixed code if available
            fixed_code_section = ""
            if validation_result.fixed_code:
                fixed_code_section = f"""
### 🔧 Auto-Fixed Code Available

The following code has automatic fixes applied. Review and retry:

```javascript
{validation_result.fixed_code}
```
"""

            return f"""🚫 **VALIDATION FAILED - NUGGET NOT CREATED**

Static validation detected errors in the generated code. The nugget was **NOT** created to prevent deploying invalid code.

### ❌ Errors ({len(errors)})
{chr(10).join(error_details)}

{"### ⚠ Warnings (" + str(len(warnings)) + ")" + chr(10) + chr(10).join(warning_details) if warnings else ""}

### Generated Code (REJECTED)
```javascript
{code}
```
{fixed_code_section}
### Discovered Functions Used
{', '.join(discovered_functions)}

### Next Steps
1. Review the errors above
2. Call `search_ez_functions` again if you need different functions
3. Call `create_nugget` again with corrected parameters

**Note**: This validation is mandatory. To bypass (NOT RECOMMENDED), set `skip_validation: true`.
"""

    label = custom_label or auto_label
    description = auto_description
    prompt = custom_prompt or description
    func_name_key = label.replace(" ", "_")

    # ================================================================
    # STEP 1: GENERATE FILE CONTENT (NO DIRECT WRITES)
    # Files are NOT written by MCP - Cascade must write them to trigger hooks
    # ================================================================
    nugget_file_content = generate_nugget_file_content(code, label, agent_id)
    env_file_content = generate_env_file_content(jwt_token, agent_id, env)

    # Generate file paths for Cascade to use
    nugget_file_path = None
    env_file_path = None
    if workspace_path:
        nugget_file_path = generate_nugget_file_path(label, agent_id, workspace_path)
        env_file_path = os.path.join(workspace_path, ".env")

    # ================================================================
    # STEP 2: API CALLS (create or update nugget on Eliza)
    # ================================================================
    base_url = COGENGINE_URLS.get(env, COGENGINE_URLS["QA"])
    headers = {
        "Authorization": f"Bearer {jwt_token}",
        "Content-Type": "application/json",
        "x-jwt-assertion": jwt_token,
        "REQUESTER-ID": "MCP_SERVER"
    }

    # ================================================================
    # STEP 2a: CHECK FOR EXISTING NUGGET (Upsert Logic)
    # Match on: 1) label (name), 2) description (instruction)
    # If a matching nugget exists, UPDATE instead of CREATE
    # ================================================================
    existing_nugget_id = None
    existing_nugget_label = None
    match_reason = None

    def _normalize(text: str) -> str:
        """Normalize text for matching - lowercase, strip whitespace."""
        return (text or "").lower().strip()

    def _keywords_match(requirement: str, target_text: str) -> bool:
        """
        Check if keywords from requirement appear in target text.
        Returns True if at least 2 keywords match OR 50%+ of keywords match.
        """
        if not requirement or not target_text:
            return False
        # Extract meaningful words (3+ chars) from requirement
        req_words = set(word.lower() for word in re.findall(r'\b\w{3,}\b', requirement))
        target_lower = target_text.lower()
        # Count matching keywords
        matches = sum(1 for word in req_words if word in target_lower)
        return matches >= 2 or (len(req_words) > 0 and matches / len(req_words) >= 0.5)

    try:
        list_url = f"{base_url}/agents/{agent_id}/nuggets/list"
        list_resp = requests.post(list_url, json={"offset": 0, "limit": 100},
                                   headers=headers, verify=False, timeout=30)
        if list_resp.status_code == 200:
            list_data = list_resp.json()
            nuggets = list_data.get("data", list_data.get("nuggets", []))

            # Priority 1: Exact label match (case-insensitive)
            for nugget in nuggets:
                nugget_label_val = nugget.get("label", "")
                if _normalize(nugget_label_val) == _normalize(label):
                    existing_nugget_id = nugget.get("agentNuggetId")
                    existing_nugget_label = nugget_label_val
                    match_reason = "label"
                    break

            # Priority 2: Description/prompt match (if no label match found)
            if not existing_nugget_id and requirement:
                for nugget in nuggets:
                    nugget_desc = nugget.get("description", "")
                    nugget_prompt = nugget.get("prompt", "")
                    # Check if requirement keywords match description or prompt
                    if _keywords_match(requirement, nugget_desc) or _keywords_match(requirement, nugget_prompt):
                        existing_nugget_id = nugget.get("agentNuggetId")
                        existing_nugget_label = nugget.get("label", "")
                        match_reason = "description"
                        break

    except Exception as e:
        # If list fails, proceed with create (safer default)
        pass

    required_params = [p["paramNameKey"] for p in custom_params if not p.get("optional", False)]

    # Nugget payload (used for both create and update)
    nugget_payload = {
        "agentId": agent_id,
        "agentDocId": "none",
        "label": label,
        "description": description,
        "prompt": prompt,
        "status": "active",
        "call": {"@type": "code", "language": "JavaScript", "code": code},
        "params": custom_params,
        "requiredParams": required_params,
        "controlFlags": [],
        "metadata": {},
        "returnResultDirectly": False
    }

    # ================================================================
    # STEP 2b: UPSERT - Update existing or Create new
    # ================================================================
    nugget_action = "CREATED"  # Track whether we created or updated

    if existing_nugget_id:
        # UPDATE existing nugget using PUT endpoint
        update_url = f"{base_url}/agents/{agent_id}/nuggets/{existing_nugget_id}"
        try:
            update_resp = requests.put(update_url, json=nugget_payload, headers=headers, verify=False, timeout=30)
            if update_resp.status_code == 200:
                updated = update_resp.json()
                nugget_id = updated.get("agentNuggetId", existing_nugget_id)
                nugget_action = "UPDATED"
            else:
                return f"""❌ NUGGET UPDATE FAILED (HTTP {update_resp.status_code})

Attempted to update existing nugget: {existing_nugget_id} (label: "{existing_nugget_label}")

Error: {update_resp.text}

Generated Code:
```javascript
{code}
```
"""
        except Exception as e:
            return f"❌ NUGGET UPDATE ERROR: {str(e)}"
    else:
        # CREATE new nugget using POST endpoint
        create_url = f"{base_url}/agents/{agent_id}/nuggets/"
        nugget_payload["agentNuggetId"] = ""  # Empty for create
        try:
            create_resp = requests.post(create_url, json=nugget_payload, headers=headers, verify=False, timeout=30)
            if create_resp.status_code == 200:
                created = create_resp.json()
                nugget_id = created.get("agentNuggetId")
                nugget_action = "CREATED"
            else:
                return f"""❌ NUGGET CREATE FAILED (HTTP {create_resp.status_code})

Error: {create_resp.text}

Generated Code:
```javascript
{code}
```
"""
        except Exception as e:
            return f"❌ NUGGET CREATE ERROR: {str(e)}"

    if not nugget_id:
        return f"❌ Failed to {nugget_action.lower()} nugget - no nugget_id returned"

    # STEP 2: Create function (if make_callable=True)
    func_id = None
    if make_callable:
        func_url = f"{base_url}/agents/{agent_id}/functions"
        func_payload = {
            "agentId": agent_id,
            "agentDocId": "none",
            "funcNameKey": func_name_key,
            "label": label,
            "prompt": prompt,
            "functionType": "NUGGET",
            "nuggetId": nugget_id,
            "includeTotal": False,
            "excludeFromHistory": False,
            "params": custom_params,
            "returnResultDirectly": False
        }

        try:
            func_resp = requests.post(func_url, json=func_payload, headers=headers, verify=False, timeout=30)
            if func_resp.status_code == 200:
                func_data = func_resp.json()
                func_id = func_data.get("agentFunctionId")
        except Exception as e:
            pass  # Function creation is optional

    # STEP 3: Validate by executing (with rollback on failure)
    call_url = f"{base_url}/agents/{agent_id}/nuggets/{nugget_id}/call"
    runtime_success = False
    validation_output = None

    try:
        call_resp = requests.post(call_url, json=test_data, headers=headers, verify=False, timeout=60)
        if call_resp.status_code == 200:
            validation_output = call_resp.text[:500]
            runtime_success = True
        else:
            validation_output = f"HTTP {call_resp.status_code}: {call_resp.text[:300]}"
    except Exception as e:
        validation_output = f"Exception: {str(e)}"

    # ROLLBACK: If runtime validation failed, delete the nugget and function
    if not runtime_success:
        rollback_msg = ""
        # Delete function first (if created)
        if func_id:
            try:
                del_func_url = f"{base_url}/agents/{agent_id}/functions/{func_id}"
                requests.delete(del_func_url, headers=headers, verify=False, timeout=10)
                rollback_msg += f" - Deleted function {func_id}\n"
            except:
                rollback_msg += f" - Failed to delete function {func_id}\n"

        # Delete nugget
        try:
            del_nugget_url = f"{base_url}/agents/{agent_id}/nuggets/{nugget_id}"
            requests.delete(del_nugget_url, headers=headers, verify=False, timeout=10)
            rollback_msg += f" - Deleted nugget {nugget_id}\n"
        except:
            rollback_msg += f" - Failed to delete nugget {nugget_id}\n"

        return f"""❌ **RUNTIME VALIDATION FAILED - NUGGET ROLLED BACK**

The nugget was created but failed runtime validation. It has been **deleted** to prevent broken code from being deployed.

### Runtime Error
{validation_output}

### Rollback Actions
{rollback_msg}
### Generated Code (FAILED)
```javascript
{code}
```

### Test Data Used
```json
{json.dumps(test_data, indent=2)}
```

### Discovered Functions
{', '.join(discovered_functions)}

### Next Steps
1. Review the runtime error above
2. Check if the ez* functions require configuration (secrets, data sources, etc.)
3. Call `search_ez_functions` again if needed
4. Call `create_nugget` again with corrected parameters
"""

    # Build validation status
    validation_status = "✅ Static validation PASSED" if not skip_validation else "⚠ Static validation SKIPPED"

    # ================================================================
    # STEP 4: BUILD EXPLICIT FILE WRITE INSTRUCTIONS FOR CASCADE
    # This ensures files are written via Cascade's edit tools, triggering hooks
    # ================================================================
    file_write_instructions = ""
    if workspace_path and nugget_file_path:
        file_write_instructions = f"""
## 📁 REQUIRED: Write Files to Disk

**You MUST write these files using your edit tools** to trigger validation hooks.

### File 1: Nugget Code
**Path**: `{nugget_file_path}`

```javascript
{nugget_file_content}
```

### File 2: Environment Credentials
**Path**: `{env_file_path}`

```
{env_file_content}
```

**⚠ IMPORTANT**: Use `write_to_file` or `edit` tool to create these files. Do NOT skip this step.
The `post_write_code` hook will run additional validation when you write these files.

---
"""
    else:
        file_write_instructions = """
## ⚠ Files Not Written

No `workspace_path` was provided, so file paths could not be generated.
To enable file writing with hook validation, call `create_nugget` with:

workspace_path: "/absolute/path/to/your/workspace"

---
"""

    # Build action-specific message
    if nugget_action == "UPDATED":
        if match_reason == "label":
            match_info = f"matched by label: \"{existing_nugget_label}\""
        elif match_reason == "description":
            match_info = f"matched by description/instruction (label: \"{existing_nugget_label}\")"
        else:
            match_info = f"label: \"{existing_nugget_label}\""
        action_msg = f"✅ **NUGGET UPDATED AND VALIDATED**\n\n📝 *Updated existing nugget ({match_info})*"
    else:
        action_msg = "✅ **NUGGET CREATED AND VALIDATED**"

    return f"""{action_msg}

{validation_status}
✅ Runtime validation PASSED

| Field | Value |
|-------|-------|
| **Action** | {nugget_action} |
| **Nugget ID** | `{nugget_id}` |
| **Label** | {label} |
| **Agent** | `{agent_id}` |
{f"| **Function ID** | `{func_id}` |" if func_id else ""}
{f"| **Function Name** | `{func_name_key}` |" if func_id else ""}

### Discovered Functions Used
{', '.join(discovered_functions)}

### Generated Code
```javascript
{code}
```

### Runtime Validation Output
```
{validation_output}
```

### Test Data
```json
{json.dumps(test_data, indent=2)}
```

The nugget is now **live** on the agent{" and callable as a tool" if func_id else ""}.
{file_write_instructions}
"""